version: '3.7'

 # 컴퓨터 이름
services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3001:3001
    env_file:
      - ./.env.docker

  # 컴퓨터 이름
  my-database:
    # platform: linux/86_64
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: noahailey
      POSTGRES_DB: postgres
    ports:
      - 5432:5432